export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_LIST_OF_GAMES = 'GET_LIST_OF_GAMES';
export const SHOW_MODAL_ADD_GAME_PROFILE = 'SHOW_MODAL_ADD_GAME_PROFILE';
export const SET_SELECTED_GAME = 'SET_SELECTED_GAME';