# File contents of "ios/Podfile"
platform :ios, '9.0'

# The target name is most likely the name of your project.
target 'QaplaReactNative' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTImage'
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  #pod 'RNAnalyticsIntegration-Mixpanel', :path => '../node_modules/@segment/analytics-react-native-mixpanel'
  #pod 'RNAnalyticsIntegration-Amplitude', :path => '../node_modules/@segment/analytics-react-native-amplitude'

  pod 'Firebase/Core', '~> 6.9.0'

  pod 'Segment-Firebase', '~>2.0'

  pod 'Analytics', '~> 3.0'

  pod 'Firebase/Messaging'

  pod 'Firebase/Functions'

  pod 'Firebase/Storage'

  pod 'Firebase/Database'

  pod 'Firebase/Auth'
  
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios' 

  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end

target 'QaplaReactNative-tvOS' do
  # Pods for tt3-tvOS

  target 'QaplaReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
