import { StyleSheet } from 'react-native'
import { widthPercentageToPx } from '../../utilities/iosAndroidDim'

export default styles = StyleSheet.create({
	profileView: {
		backgroundColor: 'rgb(13, 16, 33)',
		flex: 1
	},
	qoinsView: {
		alignSelf: 'flex-start',
		width: widthPercentageToPx(30),
		marginLeft: 40,
		flexDirection: 'row',
		alignItems: 'center'
	},
	qoinsImage: {
		width: 24,
		height: 24
	},
	textThreeText: {
		color: '#FFF',
		fontSize: 36,
		marginLeft: 8
    },
    bitsCardContainer: {
		marginTop: 12,
        marginLeft: 24,
        marginRight: 30,
        flexDirection: 'row',
        justifyContent: 'space-between'
    },
	bitsModuleView: {
		backgroundColor: 'rgb(59, 75, 249)',
		borderRadius: 20,
		shadowColor: 'rgba(0, 0, 0, 0.25)',
		shadowRadius: 10,
        shadowOpacity: 1,
        marginTop: 16,
		width: widthPercentageToPx(40)
	},
	infoImage: {
		width: 24,
		height: 24,
		marginLeft: 12,
		marginTop: 12
    },
    bitsValueContainer: {
        marginLeft: 16,
        marginTop: 12
    },
	bitsTitle: {
		color: '#FFF',
		fontSize: 16
	},
	bitsNumber: {
		color: '#FFF',
		fontSize: 40
	},
	buttonView: {
		backgroundColor: 'rgb(108, 122, 229)',
		borderRadius: 18.5,
		flexDirection: 'row',
		justifyContent: 'center',
		padding: 0,
        marginTop: 18,
		marginLeft: 18,
		marginRight: 18
	},
	supportText: {
		color: '#FFF',
        fontSize: 16,
        marginTop: 8,
        marginBottom: 8,
        textAlign: 'center'
	},
	bits3dIconImage: {
		resizeMode: 'center',
		position: 'absolute',
		left: 120
	},
	levelModalView: {
		width: 120,
		height: 152,
		marginTop: 58,
	},
	levelCircleView: {
		borderRadius: 59.5,
		borderWidth: 7,
		borderColor: 'rgb(31, 39, 80)',
		borderStyle: 'solid',
		position: 'absolute',
		left: 0,
		right: 0,
		top: 0,
		height: 119,
	},
	levelText: {
		color: 'white',
		fontSize: 12,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 16,
		position: 'absolute',
		alignSelf: 'center',
		top: 70,
	},
	levelValueText: {
		color: 'white',
		fontSize: 48,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 60,
		position: 'absolute',
		alignSelf: 'center',
		top: 12,
	},
	expText: {
		color: '#FFF',
		fontSize: 16,
		alignSelf: 'center',
		marginTop: 12
	},
	prize1View: {
		backgroundColor: 'rgb(20, 22, 55)',
		borderRadius: 20,
		width: 165,
		height: 165,
	},
	heartFourImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginBottom: 3,
	},
	heartFiveImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginLeft: 8,
		marginBottom: 3,
	},
	halfLifeIconImage: {
		resizeMode: 'center',
		width: 20,
		height: 20,
		marginLeft: 7,
	},
	prizeBodyTwoText: {
		color: 'white',
		fontSize: 12,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 16,
		position: 'absolute',
		left: 16,
		width: 126,
		top: 85,
	},
	prizeTitleTwoText: {
		color: 'white',
		fontSize: 18,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 22,
		letterSpacing: 0.29,
		paddingTop: 4,
		position: 'absolute',
		left: 16,
		width: 90,
		top: 16,
	},
	prize2View: {
		backgroundColor: 'rgb(20, 21, 57)',
		borderRadius: 20,
		width: 165,
		height: 165,
		alignItems: 'flex-start',
	},
	prizeTitleText: {
		color: 'white',
		fontSize: 22,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 22,
		letterSpacing: 0.35,
		paddingTop: 4,
		marginLeft: 18,
		marginTop: 16,
	},
	heartImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
	},
	heartTwoImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginLeft: 8,
	},
	heartThreeImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginLeft: 8,
	},
	prizeBodyText: {
		color: 'white',
		fontSize: 12,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 14,
		paddingTop: 1,
		position: 'absolute',
		left: 0,
		width: 121,
		top: 0,
	},
	slideUpModalView: {
		backgroundColor: 'rgb(59, 75, 249)',
		shadowColor: 'rgba(0, 0, 0, 0.25)',
		shadowRadius: 20,
		shadowOpacity: 1,
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		height: 241,
	},
	slideUpIndicatorView: {
		backgroundColor: 'rgb(133, 142, 243)',
		borderRadius: 2,
		alignSelf: 'center',
		width: 93,
		height: 4,
	},
	reward3dIconImage: {
		resizeMode: 'center',
		width: 58,
		height: 58,
	},
	rewardsText: {
		color: 'white',
		fontSize: 22,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'left',
		lineHeight: 28,
		letterSpacing: 0.35,
		alignSelf: 'flex-start',
	},
	barView: {
		backgroundColor: 'white',
		opacity: 0.25,
		borderRadius: 4,
		position: 'absolute',
		right: 0,
		width: 260,
		top: 0,
		height: 8,
	},
	progressView: {
		backgroundColor: 'rgb(0, 255, 222)',
		borderRadius: 4,
		position: 'absolute',
		left: 0,
		width: 130,
		top: 0,
		height: 8,
	},
	progressBarIconImage: {
		opacity: 0.25,
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginRight: 1,
		marginTop: 7,
	},
	heartSixImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginTop: 3,
	},
	heartSevenImage: {
		resizeMode: 'center',
		width: 18,
		height: 15,
		marginLeft: 8,
		marginTop: 3,
	},
	halfLifeImage: {
		resizeMode: 'center',
		width: 20,
		height: 20,
		marginLeft: 7,
	},
	progressProportionText: {
		color: 'white',
		fontSize: 11,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'right',
		lineHeight: 13,
		letterSpacing: 0.07,
		marginTop: 2,
	},
	infoCircleImage: {
		resizeMode: 'center',
		position: 'absolute',
		alignSelf: 'center',
		width: 20,
		top: 62,
		height: 20,
	},
	bottomNavBarView: {
		backgroundColor: 'rgb(13, 16, 33)',
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		height: 80,
	},
	communityView: {
		position: 'absolute',
		alignSelf: 'center',
		width: 125,
		top: 12,
		height: 46,
	},
	commentImage: {
		resizeMode: 'center',
		position: 'absolute',
		alignSelf: 'center',
		width: 25,
		top: 3,
		height: 25,
	},
	communityText: {
		color: 'white',
		fontSize: 11,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'center',
		opacity: 0.25,
		position: 'absolute',
		left: 32,
		right: 32,
		top: 26,
	},
	eventsView: {
		width: 125,
		height: 46,
	},
	controllerImage: {
		resizeMode: 'center',
		position: 'absolute',
		alignSelf: 'center',
		width: 30,
		top: 6,
		height: 20,
	},
	eventsText: {
		opacity: 0.25,
		color: 'white',
		fontSize: 11,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'center',
		position: 'absolute',
		left: 44,
		right: 44,
		top: 26,
	},
	profileTwoView: {
		width: 125,
		height: 46,
	},
	userImage: {
		resizeMode: 'center',
		position: 'absolute',
		alignSelf: 'center',
		width: 23,
		top: 1,
		height: 28,
	},
	profileText: {
		color: 'rgb(61, 249, 223)',
		fontSize: 11,
		fontStyle: 'normal',
		fontWeight: 'normal',
		textAlign: 'center',
		position: 'absolute',
		left: 45,
		right: 45,
		top: 26,
	},
})