import { StyleSheet } from 'react-native';
import Colors from '../../utilities/Colors';
import { heightPercentageToPx, widthPercentageToPx } from '../../utilities/iosAndroidDim';

export default styles = StyleSheet.create({
    whiteText: {
        color: '#fff',
    },
    container: {
        flex: 1,
        backgroundColor: '#0D1021',
        marginBottom: '20%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#00000D',
    },
    cardContainer: {
        alignItems: 'center',
        justifyContent: 'flex-end',
        overflow: 'hidden',
        height: 400,
        width: '90%',
        borderRadius: 25,
        backgroundColor: '#f0f',
    },
    backgroundImage: {
        position: 'absolute',
        flex: 1,
        width: '100%',
        height: '100%',
        top: 0,
    },
    backgroundAttenuation: {
        flex: 1,
        position: 'absolute',
        backgroundColor: '#0004',
        width: '100%',
        height: '100%',
    },
    cardTextContainer: {
        marginTop: 12,
    },
    cardTitleText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        lineHeight: 24,
        letterSpacing: 1,
        textAlign: 'center',
        maxWidth: '70%',
    },
    cardSubtitleText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
        lineHeight: 17,
        textAlign: 'center',
        marginTop: 16,
    },
    cardButton: {
        backgroundColor: '#3B4BF9',
        paddingHorizontal: '24%',
        paddingVertical: '6%',
        borderRadius: 100,
        marginTop: '13%',
        marginBottom: 30,
    },
    cardTextButton: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '700',
        lineHeight: 22,
        letterSpacing: 0.492000013589859,
        textAlign: 'center',
    },
    addTagModal: {
        backgroundColor: '#141539',
        width: '100%',
        bottom: 0,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingTop: 16,
    },
    addTagHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    closeButtonCompensation: {
        marginRight: -40,
    },
    headerText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
        textAlign: 'center',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    scrollView: {
        marginTop: 32,
        maxHeight: 225,
        maxWidth: '85%',
        alignSelf: 'center',
        borderRadius: 10,
        overflow: 'hidden',
    },
    textInputContainer: {
        backgroundColor: '#0D1021',
        width: '90%',
        height: 40,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 40,
        borderRadius: 18,
        paddingHorizontal: 16,
    },
    textInput: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    tagTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 16,
    },
    tagText: {
        color: '#FFFFFF99',
        fontSize: 10,
        fontWeight: '500',
        lineHeight: 12,
        marginLeft: 4,
    },
    chipList: {
        paddingLeft: 16,
        marginTop: 16,
    },
    tipText: {
        color: '#FFFFFF99',
        fontSize: 12,
        fontWeight: '500',
        lineHeight: 14,
        textAlign: 'center',
    },
    uploadButton: {
        backgroundColor: '#00FFDD',
        width: 270,
        height: 75,
        borderRadius: 38,
        alignSelf: 'center',
        justifyContent: 'center',
        marginTop: 32,
    },
    uploadButtonText: {
        color: '#0D1021',
        fontSize: 17,
        fontWeight: '700',
        lineHeight: 22,
        letterSpacing: 0.492000013589859,
        textAlign: 'center',
    },
    finalModalContainer: {
        flex: 1,
        backgroundColor: '#0D1021',
        justifyContent: 'center',
        alignItems: 'center',
    },
    finalModalCard: {
        backgroundColor: '#141539',
        width: '90%',
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    finalCardModalTitle: {
        color: '#fff',
        fontSize: 24,
        fontWeight: '700',
        lineHeight: 29,
        letterSpacing: -0.7200000286102295,
        textAlign: 'center',
    },
    finalCardModalSubtitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
        lineHeight: 19,
        letterSpacing: 0.2545454502105713,
        textAlign: 'center',
        maxWidth: '80%',
    },
    finalCardButton: {
        backgroundColor: '#3B4BF9',
        paddingVertical: 26,
        paddingHorizontal: 75,
        marginTop: 32,
        borderRadius: 38,
    },
    finalCardButtonText: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '700',
        lineHeight: 22,
        letterSpacing: 0.492000013589859,
        textAlign: 'center',
    },
});