import { StyleSheet } from 'react-native';
import { getScreenSizeMultiplier } from '../../utilities/iosAndroidDim';
import Colors from '../../utilities/Colors';

export default styles = StyleSheet.create({
    formularioCheersView: {
        backgroundColor: 'white',
        flex: 1,
    },
    bgView: {
        backgroundColor: 'rgb(4, 6, 22)',
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: 1093,
    },
    arrowLeftCircleCopyImage: {
        backgroundColor: '#141539',
        resizeMode: 'center',
        width: getScreenSizeMultiplier() * 40,
        height: getScreenSizeMultiplier() * 40,
        marginLeft: getScreenSizeMultiplier() * 16,
        borderRadius: 100,
    },
    modalBgView: {
        width: '100%',
        height: '100%',
    },
    modalBgViewLinearGradient: {
        shadowColor: 'rgba(0, 0, 0, 0.14)',
        shadowRadius: 5,
        shadowOpacity: 1,
        alignSelf: 'stretch',
        height: getScreenSizeMultiplier() * 981,
        borderTopLeftRadius: getScreenSizeMultiplier() * 40,
        borderTopRightRadius: getScreenSizeMultiplier() * 40,
    },
    titleText: {
        backgroundColor: 'transparent',
        color: 'white',
        fontSize: getScreenSizeMultiplier() * 30,
        fontStyle: 'normal',
        fontWeight: 'bold',
        textAlign: 'left',
        lineHeight: getScreenSizeMultiplier() * 48,
        alignSelf: 'flex-start',
        marginLeft: getScreenSizeMultiplier() * 7,
    },
    bodyText: {
        backgroundColor: 'transparent',
        color: 'white',
        fontSize: getScreenSizeMultiplier() * 14,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'left',
        lineHeight: getScreenSizeMultiplier() * 26,
        letterSpacing: getScreenSizeMultiplier() * 0.25,
        alignSelf: 'flex-start',
        width: getScreenSizeMultiplier() * 291,
        marginLeft: getScreenSizeMultiplier() * 7,
        marginTop: getScreenSizeMultiplier() * 30,
    },
    streamerSelectCardView: {
        borderRadius: 16,
        shadowColor: 'rgba(0, 0, 0, 0.14)',
        shadowRadius: 5,
        shadowOpacity: 1,
        marginVertical: getScreenSizeMultiplier() * 9,
        width: getScreenSizeMultiplier() * 160,
        height: getScreenSizeMultiplier() * 110,
    },
    streamerSlectCardLinearGradient: {
        flex: 1,
        borderRadius: 16,
    },
    streamerText: {
        color: 'white',
        fontSize: getScreenSizeMultiplier() * 16,
        fontStyle: 'normal',
        fontWeight: 'bold',
        textAlign: 'right',
        lineHeight: getScreenSizeMultiplier() * 20,
        marginRight: getScreenSizeMultiplier() * 16,
        marginBottom: getScreenSizeMultiplier() * 15,
    },
    avatarImage: {
        resizeMode: 'center',
        backgroundColor: 'transparent',
        alignSelf: 'flex-start',
        width: getScreenSizeMultiplier() * 44,
        height: getScreenSizeMultiplier() * 44,
        marginLeft: 16,
        marginTop: 16,
        borderRadius: 100,
    },
    graciasText: {
        color: 'white',
        fontSize: getScreenSizeMultiplier() * 30,
        fontStyle: 'normal',
        fontWeight: 'bold',
        textAlign: 'left',
        lineHeight: getScreenSizeMultiplier() * 30,
        marginTop: getScreenSizeMultiplier() * 12.4,
    },
    prizeTitleText: {
        color: 'white',
        fontSize: getScreenSizeMultiplier() * 22,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        lineHeight: getScreenSizeMultiplier() * 26,
        letterSpacing: getScreenSizeMultiplier() * 0.35,
        marginTop: getScreenSizeMultiplier() * 17,
    },
    continueButtonText: {
        flex: 1,
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.backgroundDarkModal,
        textAlign: 'center',
        textAlignVertical: 'center',
        marginTop: 34,
        marginBottom: 34
    }
});
